-- Create seed_logs table for chunk-level debug visibility
CREATE TABLE IF NOT EXISTS public.seed_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id uuid NOT NULL,
  chunk_index integer NOT NULL,
  status text NOT NULL CHECK (status IN ('started','success','failed','rate_limited')),
  error_message text,
  retry_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS seed_logs_document_id_idx
  ON public.seed_logs (document_id, created_at DESC);

CREATE INDEX IF NOT EXISTS seed_logs_created_at_idx
  ON public.seed_logs (created_at DESC);

ALTER TABLE public.seed_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can view seed logs"
  ON public.seed_logs
  FOR SELECT
  TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can manage seed logs"
  ON public.seed_logs
  FOR ALL
  TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (public.has_role(auth.uid(), 'admin'::app_role));

-- Add per-document live debug fields
ALTER TABLE public.documents
  ADD COLUMN IF NOT EXISTS current_chunk_index integer,
  ADD COLUMN IF NOT EXISTS last_error text;